#pragma once
#include <stdio.h>
#include <pcap.h>
#include "ethhdr.h"
#include "ip.h"
#include "iphdr.h"
#include "mac.h"
#include "tcphdr.h"
#include <string>
#include <ifaddrs.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <unistd.h>
